services:
    database:
        image: mariadb:10.4.30
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - database_data:/var/lib/mysql
            - ./database/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
            TZ: America/Sao_Paulo
        restart: unless-stopped

    nginx:
        image: nginx:latest
        ports:
            - "8001:8001"
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./:/bebeu-api
        depends_on:
            - bebeu-api
        restart: unless-stopped

    bebeu-api:
        build: .
        working_dir: /bebeu-api
        volumes:
            - ./:/bebeu-api
            - ./config/php.development.ini:/usr/local/etc/php/php.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        entrypoint: sh -c "composer install && php-fpm"

volumes:
    database_data:
